Stage 3 - Dav 1
TYPO3-Documentation/TYPO3CMS-Guide-CommunityExpansionCommittee pull request #776
Opened 2024-06-07 16:20 UTC by sbusemann

resolves #43

2024-06-09 18:09 UTC, mabolek requested changes

2024-06-09 18:09 UTC, mabolek commented on Documentation/Stage-3-Deployment/Day-1/Lesson-1.rst
> +* Understand the result of different CI/CD Tools
This looks like a theoretical, rathern than practical, goal.

2024-06-09 18:09 UTC, mabolek commented on Documentation/Stage-3-Deployment/Day-1/Lesson-2.rst
> +* Understand how distributed collaboration works
This looks like a theoretical, rathern than practical, goal.

2024-06-26 06:53 UTC, sbusemann commented
I updated the branch for the requested changes

2024-06-27 17:11 UTC, mabolek approved these changes

2024-06-27 17:11 UTC, merged